Step1 vanilla js
Mobwiser-IT-Academy/Share-Humanity-Rita-Silva pull request #2
Opened 2020-10-07 12:44 UTC by RitaSilva28

2020-10-08 07:37 UTC, fabioaarito requested changes

2020-10-08 07:37 UTC, fabioaarito commented on HTML/coronavirus.html
> +    <link rel="stylesheet" href="/CSS/coronavirus.css">
Aqui deves usar antes ```../CSS/coronavirus.css``` porque o browser interpreta o / como a "raiz" da tua máquina e não a "raiz" do teu projeto.

Se usares o ```../``` ele sabe que tem de andar uma diretoria para trás e depois entrar na diretoria CSS e ir buscar o ficheiro coronavirus.

Isto aplica-se a todos os links que tens para ficheiros no teu projeto :)

2020-10-08 07:37 UTC, fabioaarito commented on JS/share.js
> +let issues = {
Eu aqui optaria por uma estrutura de dados diferente mais fácil de iterar, de manter e num futuro próximo guardar na base de dados.

Conceptualmente, o que tu tens são "issues" ou seja uma lista de issues. Assim guardaria isto numa estrutura deste género:

```
const issues = [
{
  title: 'Coronavirus Pandemic',
  src: 'https://...',
  description: 'Coronavirus Pandemic....',
  href: 'coronavirus.html'
},
{...},
]
```

2020-10-08 07:37 UTC, fabioaarito commented on JS/share.js
> +  for (i=0; i<8; i++){
Aqui irias logo iterar o tamanho da lista de issues. Se adicionares um elemento à lista não tens de vir alterar este número :)

2020-10-08 07:37 UTC, fabioaarito commented on JS/share.js
> +  div.appendChild(h5);
Na geração do HTML (de cada issue) podes experimentar usar um approach diferente que é capaz de ser mais simples.

Guardas o html de todos os issues numa variável e depois vais adicionando a essa variável o html de cada issue da seguinte forma;

```
cont issuesHtml = '';

for(let i = 0; i < issues.length; i++) {
// Isto é só um exemplo. Estou a usar uma feature do javascript chamada template strings onde posso concatenar facilmente valores de variáveis dentro de uma string
issuesHTML += `<div>${issues[i].title}</div>`;
}
// Depois no final do for posso adicionar os issuesHTML dentro do meu container
var container = document.getElementById('issuesContainer');
container.innerHTML = issuesHtml;
```

2020-10-09 13:22 UTC, fabioaarito requested changes

2020-10-09 13:22 UTC, fabioaarito commented on HTML/coronavirus.html
> +    <img class="covid19" src="/images/covid19.jpg" alt="Covid19">
aqui também deverá ser ```../``` e nas outras imagens, ficheiros CSS e JS também. A regra aplica-se a qualquer caminho relativo para um ficheiro.

2020-10-09 13:22 UTC, fabioaarito commented on JS/share.js
> +const issues = [{
Perfeito :D

2020-10-09 13:22 UTC, fabioaarito commented on JS/share.js
> +  var container = document.getElementById('issues-container');
Isto mesmo. O código ficou muito mais clean :)

2020-10-09 13:22 UTC, fabioaarito commented on JS/share.js
> +let container = document.getElementById("issues-container");
Porque precisas deste código aqui e as funções abaixo?

2020-10-09 15:21 UTC, RitaSilva28 commented on JS/share.js
> +let container = document.getElementById("issues-container");
As funções abaixo são para o filtro dos issues

2020-10-10 08:34 UTC, fabioaarito requested changes

2020-10-12 19:09 UTC, fabioaarito requested changes

2020-10-12 19:09 UTC, fabioaarito commented on JS/share.js
> +  for (let i = 0; i < issues.length; i++) {
Podes fazer isto só com 1 for. Percorres os issues e se a condição for true adicionas aos issuesHtml.

2020-10-12 19:09 UTC, fabioaarito commented on JS/share.js
> +  for (let i = 0; i < issues.length; i++) {
Podes até ter só uma função de createHTML que permite a passagem de um filtro de categoria e/ou um filtro de texto
```
createHtml(filterCategory, filterName) {

for(issues) {
  if((!filterCategory || categoryConditionIsTrue) && (!filterName || nameConditionIsTrue)) {
   issuesHTML += ....
  }
 }
}

filterByType(type) {
 createHtml(filterCategory);
}

filterByName(input) {
createHtml(undefined, filterName);
}
```

Deixei-te este pseudocodigo para te ajudar. Diz-me pff se percebes :)

2020-10-15 08:24 UTC, fabioaarito approved these changes

2020-10-15 13:41 UTC, merged